<a href="https://colab.research.google.com/github/umermaher/20SW033-DSA-Project/blob/main/Mid_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
list_of_random_things = [1,3.2,'a String',False]
print(list_of_random_things[0:4]) #slicing

[1, 3.2, 'a String', False]


In [24]:
#list functions
l = [1,3.2,'a String',False]
cities = ["Hyd","Karachi","Mirpur"]
numbers = [2,3.2,1,3]
print(len(l))
print(max(numbers))
print(sorted(numbers))
cities.append("Islamabad")
print(" | ".join(cities))

4
3.2
[1, 2, 3, 3.2]
Hyd | Karachi | Mirpur | Islamabad


In [1]:
dictionary = {
    "val1": 1,
    "val2": "Helo"
}
print(dictionary)

{'val1': 1, 'val2': 'Helo'}


In [5]:
num = input("Enter a number: ")
if int(num) % 2 == 0:
  print("Even")
else :
  print("Odd")

Enter a number: 5
Odd


In [6]:
cities = ["Hyd","Karachi","Mirpur"]
for city in cities:
  print(city)

Hyd
Karachi
Mirpur


In [30]:
def is_prime(number):
  if(number<=1):
    return False
  for i in range(2, int(number**0.5) + 1):
    if(number % i == 0):
      return False

  return True

num = int(input("Enter a number: "))
if(is_prime(num)):
  print("Prime number")
else:
  print("Not a Prime number")

Enter a number: 21
Not a Prime number


# **Numpy**

In [31]:
import numpy as np

my_arr = np.array([2,5,3,9,7])
print(my_arr)

[2 5 3 9 7]


In [45]:
sized_element_array = np.array([2,5,127,9,7], np.int8) #Getting memory managemnt in hands
print(sized_element_array)

[  2   5 127   9   7]


In [52]:
my_arr = np.array([[2,5,3,9,7],[2,5,4,3,99]])
my_arr.shape

dtype('int64')

In [53]:
my_arr.dtype

dtype('int64')

In [54]:
my_arr[0,2]

3

In [56]:
my_arr[0,2] = 88
print(my_arr)

[[ 2  5 88  9  7]
 [ 2  5  4  3 99]]


# Array creation from other python structures

In [59]:
list_array = np.array([[1,2,3],[3,5,6,],[7,9,10]])
list_array

array([[ 1,  2,  3],
       [ 3,  5,  6],
       [ 7,  9, 10]])

In [60]:
list_array.dtype

dtype('int64')

In [61]:
list_array.shape

(3, 3)

In [62]:
list_array.size

9

In [63]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
lspace = np.linspace(1,30,4)
lspace

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [70]:
emp = np.empty((2,5))
emp

array([[5.02908719e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.59027810e-144],
       [3.73698426e-061, 7.48417000e-067, 6.20393924e-091,
        1.24529369e-047, 2.65716873e-312]])

In [71]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [75]:
to_reshape = np.arange(99)
to_reshape = to_reshape.reshape(3,33)
to_reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [76]:
to_reshape.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [93]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
#ar.sum()
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [94]:
ar.sum()

29

In [81]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [82]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [84]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
7
1
0


In [85]:
ar.ndim

2

In [86]:
ar.size

9

In [87]:
ar.nbytes

72

In [88]:
ar.argmax()

6

In [89]:
ar.argmin()

8

In [90]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [91]:
ar.argmax(axis=0)

array([2, 1, 1])

In [95]:
ar.argmax(axis=1)

array([2, 2, 0])

In [96]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [97]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])